site_name: Dev notes for Java
site_url: https://xkx9431.github.io/dev-notes-java/
site_author: Xu Kaixuan
site_description: Some notes for daily dev for java related

repo_name: dev-notes-java
repo_url: https://github.com/xkx9431/dev-notes-java
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 XKX

theme:
  name: material
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
  # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
  - content.code.annotate
  - navigation.indexes
  - navigation.instant
  - navigation.tabs
  - navigation.tabs.sticky
  - navigation.top
  - navigation.tracking
  - search.highlight
  - search.share
  - search.suggest
  palette:
  - scheme: default
    primary: indigo
    accent: indigo
    toggle:
      icon: material/toggle-switch-off-outline
      name: Switch to dark mode
  - scheme: slate
    primary: blue
    accent: blue
    toggle:
      icon: material/toggle-switch
      name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # - tags:
  #     tags_file: tags.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/xkx9431
    - icon: fontawesome/brands/zhihu
      link: https://www.zhihu.com/people/triumphxu
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/%E5%87%AF%E6%97%8B-%E8%A8%B1-983884103/
    # - icon: fontawesome/brands/blog
    #   link: https://xkx9431.github.io/xkx_blog/

nav:
  - Home: index.md
  - JVM:
    - JVM: jvm/index.md
    - Memory Management:
      - Memory Management: jvm/mm-overview.md
      - Introduction: jvm/mm-introduction.md




# nav:
#   - Home: index.md
#   - Internals:
#     - Overview: overview.md
#     # - Tags: tags.md
#     - SparkEnv: SparkEnv.md
#     - SparkConf: SparkConf.md
#     - SparkContext: SparkContext.md
#     - Local Properties: local-properties.md
#     - Inside Creating SparkContext: SparkContext-creating-instance-internals.md
#     - SparkStatusTracker: SparkStatusTracker.md
#     - SparkFiles: SparkFiles.md
#     - Configuration Properties: configuration-properties.md
#     - Spark Properties: spark-properties.md
#     - External Shuffle Service:
#       - external-shuffle-service/index.md